### ISSUE TITLE
Convert strings to boolean

### ISSUE THREAD

**Issue by mattrmd** [MohdRad/FEAL#1]
There are parts of the code that use strings instead of booleans, which makes the code more cluttered. For example, [this line](https://github.com/MohdRad/FEAL/blob/main/FEAL.py#L85)
```python
    if (shuf=='True'):
        df = shuffle(df)
```

should simply be
```python
    if shuf:
        df = shuffle(df)
```
with `shuf` as a [boolean](https://docs.python.org/3/library/stdtypes.html#boolean-type-bool), not a string.

**Comment by MohdRad** [comment]
Resolved
